=== oxygenxml/ebu-tt/frameworks/ebu-tt/ebu-tt-xml-schema-v.1.0.1/ebutt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2012, EBU, www.ebu.ch -->
<!-- Version of XML Schema: 1.0.1 -->
<!-- Creation: 27/06/2013 -->
<!--  The publication of the EBU-TT XML Schema for EBU-Part 1 is intended to support the implementation of the specification in EBU-Tech 3350 version 1.0. 
Please note that the EBU-TT XML Schema is a helping document and NOT normative but informative.-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ebuttdt="urn:ebu:tt:datatypes" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ebuttm="urn:ebu:tt:metadata" xmlns:ebutts="urn:ebu:tt:style" targetNamespace="http://www.w3.org/ns/ttml">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<xs:import namespace="http://www.w3.org/ns/ttml#styling" schemaLocation="styling.xsd"/>
	<xs:import namespace="http://www.w3.org/ns/ttml#parameter" schemaLocation="parameter.xsd"/>
	<xs:import namespace="urn:ebu:tt:metadata" schemaLocation="ebutt_metadata.xsd"/>
	<xs:import namespace="urn:ebu:tt:style" schemaLocation="ebutt_styling.xsd"/>
	<xs:import namespace="urn:ebu:tt:datatypes" schemaLocation="ebutt_datatypes.xsd"/>
	<xs:import namespace="http://www.w3.org/ns/ttml#metadata" schemaLocation="metadata.xsd"/>
	<xs:element name="tt">
		<xs:annotation>
			<xs:documentation>Root element of an EBU-TT XML document.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:head"/>
				<xs:element ref="tt:body"/>
			</xs:sequence>
			<xs:attribute ref="xml:space">
				<xs:annotation>
					<xs:documentation>Indicates the author’s intention of white space handling within the content of the EBU-TT document.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="ttp:timeBase" use="required"/>
			<xs:attribute ref="ttp:frameRate" use="optional"/>
			<xs:attribute ref="ttp:frameRateMultiplier" use="optional"/>
			<xs:attribute ref="ttp:markerMode" use="optional"/>
			<xs:attribute ref="ttp:dropMode"/>
			<xs:attribute ref="ttp:cellResolution"/>
			<xs:attribute ref="tts:extent">
				<xs:annotation>
					<xs:documentation>Defines the width and height of the active video the subtitles were authored for. Only length expressions in pixels shall be used.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang" use="required">
				<xs:annotation>
					<xs:documentation>The language for which the EBU-TT document is prepared. (STL mapping: Language Code (LC))</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="head">
		<xs:annotation>
			<xs:documentation>Contains metadata as well as layout and styling information that are referenced by the subtitle blocks in the body.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:metadata">
					<xs:annotation>
						<xs:documentation>Generic container for metadata information that applies to the whole document.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="tt:styling"/>
				<xs:element ref="tt:layout"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="metadata">
		<xs:annotation>
			<xs:documentation>Container for metadata information.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="styling">
		<xs:annotation>
			<xs:documentation>Container for styling information.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0"/>
				<xs:element ref="tt:style" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="style">
		<xs:annotation>
			<xs:documentation>Set of style information.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute ref="xml:id" use="required">
				<xs:annotation>
					<xs:documentation>ID of a tt:style element that is used by other elements for reference.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="style" type="xs:IDREFS">
				<xs:annotation>
					<xs:documentation>Reference to one or more other tt:style elements.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="tts:direction"/>
			<xs:attribute ref="tts:fontFamily"/>
			<xs:attribute ref="tts:fontSize"/>
			<xs:attribute ref="tts:lineHeight"/>
			<xs:attribute ref="tts:textAlign"/>
			<xs:attribute ref="tts:color"/>
			<xs:attribute ref="tts:backgroundColor"/>
			<xs:attribute ref="tts:fontStyle"/>
			<xs:attribute ref="tts:fontWeight"/>
			<xs:attribute ref="tts:textDecoration"/>
			<xs:attribute ref="tts:unicodeBidi"/>
			<xs:attribute ref="tts:padding">
				<xs:annotation>
					<xs:documentation>Padding (or inset) space on all sides of a block area generated by a tt:p element or an inline area generated by a tt:span element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="ebutts:multiRowAlign"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="layout">
		<xs:annotation>
			<xs:documentation>Container element for layout information.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0"/>
				<xs:element ref="tt:region" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="region">
		<xs:annotation>
			<xs:documentation>Defines a space or area for the display of subtitle content.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute ref="xml:id" use="required">
				<xs:annotation>
					<xs:documentation>ID of a region.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="tts:origin" use="required"/>
			<xs:attribute ref="tts:extent" use="required">
				<xs:annotation>
					<xs:documentation>Width and height of a region area. Values in percentage shall be relative to the width and height of the active picture.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="style" type="xs:IDREFS">
				<xs:annotation>
					<xs:documentation>ID(s) of one or more style element(s).</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="tts:displayAlign"/>
			<xs:attribute ref="tts:padding">
				<xs:annotation>
					<xs:documentation>Padding (or inset) space on all sides of a region area.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="tts:writingMode"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="body">
		<xs:annotation>
			<xs:documentation>Container of the subtitle and the timing information.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0"/>
				<xs:element ref="tt:div" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="ttm:agent"/>
			<xs:attribute ref="ttm:role"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="div">
		<xs:annotation>
			<xs:documentation>Logical container of textual content.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="tt:div"/>
					<xs:element ref="tt:p"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute ref="xml:id">
				<xs:annotation>
					<xs:documentation>ID of a tt:div element that may be used by an external application.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="region" type="xs:IDREF">
				<xs:annotation>
					<xs:documentation>Application of layout and style information through reference of a region.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="style" type="xs:IDREFS">
				<xs:annotation>
					<xs:documentation>ID(s) of one or more style element(s). The style information shall be applied to the enclosed content of the tt:div element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="ttm:agent"/>
			<xs:attribute ref="ttm:role"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="p">
		<xs:annotation>
			<xs:documentation>Logical paragraph.</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="tt:br"/>
					<xs:element ref="tt:span"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute ref="xml:id" use="required">
				<xs:annotation>
					<xs:documentation>Unique ID of a subtitle.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:space">
				<xs:annotation>
					<xs:documentation>Indicates the author’s intention of white space handling within the content of the tt:p element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang">
				<xs:annotation>
					<xs:documentation>Language identifier that overwrites the language identification of the enclosed subtitle content.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="region" type="xs:IDREF">
				<xs:annotation>
					<xs:documentation>Application of layout information through reference of a region.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="style" type="xs:IDREFS">
				<xs:annotation>
					<xs:documentation>ID(s) of one or more style element(s). The style information shall be applied to the enclosed content of the tt:p element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="begin" type="ebuttdt:timingType" use="required">
				<xs:annotation>
					<xs:documentation>Start point of a temporal interval associated with a tt:p element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="end" type="ebuttdt:timingType" use="required">
				<xs:annotation>
					<xs:documentation>End point of a temporal interval associated with a tt:p element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="ttm:agent"/>
			<xs:attribute ref="ttm:role"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="span">
		<xs:annotation>
			<xs:documentation>Inline element to allow the application of local style information, annotation or metadata.</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="tt:br"/>
					<xs:element ref="tt:span"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute ref="xml:space">
				<xs:annotation>
					<xs:documentation>Indicates the authors’ intention of white space handling within the content of the element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang">
				<xs:annotation>
					<xs:documentation>Language identifier that overwrites the language identification of the enclosed subtitle content.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:id">
				<xs:annotation>
					<xs:documentation>ID of a tt:span element that may be used by an external application.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="style" type="xs:IDREFS">
				<xs:annotation>
					<xs:documentation>ID(s) of one or more style element(s). The style information shall be applied to the enclosed content of the tt:span element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="begin" type="ebuttdt:timingType">
				<xs:annotation>
					<xs:documentation>Start point of a temporal interval associated with the element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="end" type="ebuttdt:timingType">
				<xs:annotation>
					<xs:documentation>End point of a temporal interval associated with the element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="ttm:agent"/>
			<xs:attribute ref="ttm:role"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="br">
		<xs:annotation>
			<xs:documentation>Forced line break.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tt:metadata" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute ref="ttm:role"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== oxygenxml/ebu-tt/frameworks/ebu-tt/sample/ebu-tt-samplefile-colours.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright (c) 2013 by Institut fuer Rundfunktechnik GmbH. 
This work is made available under the terms of the Creative Commons Attribution-ShareAlike 3.0 license, 
http://creativecommons.org/licenses/by-sa/3.0/

This sample file should illustrate the application of EBU Tech 3360, MAPPING EBU STL (TECH 3264) TO EBU-TT SUBTITLE FILES, VER. 0.9. Please note that Version 0.9 of Tech 3360 is a draft document and may be updated, replaced or obsoleted by other documents at any time. The same applies to the sample file.
--> 
<!-- v0.1.2 -->
<?xml-stylesheet type="text/css" href="../css/ebu-tt.css"?>
<tt:tt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.w3.org/ns/ttml ../ebu-tt-xml-schema-v.1.0.1/ebutt.xsd"
 xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling"
 xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ebuttm="urn:ebu:tt:metadata" ttp:timeBase="smpte"
 xml:lang="en" ttp:cellResolution="50 30" tts:extent="704px 576px" ttp:dropMode="nonDrop"
 ttp:frameRate="25" ttp:frameRateMultiplier="1 1" ttp:markerMode="discontinuous">
	<tt:head>
		<tt:metadata>
			<ebuttm:documentMetadata>
				<ebuttm:documentEbuttVersion>v1.0</ebuttm:documentEbuttVersion>
				<ebuttm:documentTotalNumberOfSubtitles>18</ebuttm:documentTotalNumberOfSubtitles>
				<ebuttm:documentMaximumNumberOfDisplayableCharacterInAnyRow>40</ebuttm:documentMaximumNumberOfDisplayableCharacterInAnyRow>
				<ebuttm:documentStartOfProgramme>00:00:00:00</ebuttm:documentStartOfProgramme>
				<ebuttm:documentCountryOfOrigin>GB</ebuttm:documentCountryOfOrigin>
				<ebuttm:documentPublisher>Institut fuer Rundfunktechnik</ebuttm:documentPublisher>
			</ebuttm:documentMetadata>
		</tt:metadata>
		<tt:styling>
			<tt:style xml:id="defaultStyle" tts:fontFamily="monospaceSansSerif" tts:fontSize="1c 1c" tts:lineHeight="normal" tts:textAlign="center" tts:color="white" tts:backgroundColor="transparent" tts:fontStyle="normal" tts:fontWeight="normal" tts:textDecoration="none"/>
			<tt:style xml:id="BlackOnWhite" tts:color="black" tts:backgroundColor="white"
				tts:fontSize="1c 2c"/>
			<tt:style xml:id="RedOnBlack" tts:color="red" tts:backgroundColor="black" tts:fontSize="1c 2c"/>
			<tt:style xml:id="GreenOnBlack" tts:color="green" tts:backgroundColor="black" tts:fontSize="1c 2c"/>
			<tt:style xml:id="YellowOnBlack" tts:color="yellow" tts:backgroundColor="black" tts:fontSize="1c 2c"/>
			<tt:style xml:id="BlueOnYellow" tts:color="blue" tts:backgroundColor="yellow" tts:fontSize="1c 2c"/>
			<tt:style xml:id="BlueOnWhite" tts:color="blue" tts:backgroundColor="white" tts:fontSize="1c 2c"/>
			<tt:style xml:id="MagentaOnBlack" tts:color="magenta" tts:backgroundColor="black" tts:fontSize="1c 2c"/>
			<tt:style xml:id="CyanOnBlack" tts:color="cyan" tts:backgroundColor="black" tts:fontSize="1c 2c"/>
			<tt:style xml:id="WhiteOnBlack" tts:color="white" tts:backgroundColor="black"
				tts:fontSize="1c 2c"/>
			<tt:style xml:id="textCenter" tts:textAlign="center"/>
		</tt:styling>
		<tt:layout>
			<tt:region xml:id="bottom" tts:origin="10% 10%" tts:extent="80% 80%" tts:padding="0c" tts:displayAlign="after" tts:writingMode="lrtb"/>
		</tt:layout>
	</tt:head>
	<tt:body>
		<tt:div style="defaultStyle">
			<tt:p xml:id="sub1" style="textCenter" region="bottom" begin="00:00:00:00" end="00:00:02:03">
				<tt:span style="WhiteOnBlack">white on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub2" style="textCenter" region="bottom" begin="00:00:02:07" end="00:00:04:07">
				<tt:span style="YellowOnBlack">yellow on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub3" style="textCenter" region="bottom" begin="00:00:04:11" end="00:00:06:14"
					><tt:span style="GreenOnBlack">green on black</tt:span></tt:p>
			<tt:p xml:id="sub4" style="textCenter" region="bottom" begin="00:00:06:18" end="00:00:08:21">
				<tt:span style="CyanOnBlack">cyan on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub5" style="textCenter" region="bottom" begin="00:00:09:00" end="00:00:11:01">
				<tt:span style="MagentaOnBlack">magenta on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub6" style="textCenter" region="bottom" begin="00:00:11:05" end="00:00:13:02">
				<tt:span style="RedOnBlack">red on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub7" style="textCenter" region="bottom" begin="00:00:13:06" end="00:00:15:02">
				<tt:span style="BlueOnYellow">blue on yellow</tt:span>
			</tt:p>
			<tt:p xml:id="sub8" style="textCenter" region="bottom" begin="00:00:15:06" end="00:00:17:05">
				<tt:span style="BlackOnWhite">black on white</tt:span>
			</tt:p>
			<tt:p xml:id="sub9" style="textCenter" region="bottom" begin="00:00:17:09" end="00:00:20:06">
				<tt:span style="WhiteOnBlack">white on black </tt:span>
				<tt:br/>
				<tt:span style="BlueOnYellow">and blue on yellow</tt:span>
			</tt:p>
			<tt:p xml:id="sub10" style="textCenter" region="bottom" begin="00:00:20:10" end="00:00:23:00">
				<tt:span style="WhiteOnBlack">a </tt:span>
				<tt:span style="RedOnBlack">red</tt:span>
				<tt:span style="WhiteOnBlack"> word</tt:span>
			</tt:p>
			<tt:p xml:id="sub11" style="textCenter" region="bottom" begin="00:00:23:04" end="00:00:26:20">
				<tt:span style="WhiteOnBlack">A </tt:span>
				<tt:span style="BlueOnYellow">blue</tt:span>
				<tt:span style="WhiteOnBlack"> word</tt:span>
				<tt:br/>
				<tt:span style="WhiteOnBlack">on yellow background.</tt:span>
			</tt:p>
			<tt:p xml:id="sub12" style="textCenter" region="bottom" begin="00:00:26:24" end="00:00:29:05"
					><tt:span style="BlueOnYellow">A blue </tt:span><tt:span style="BlueOnWhite"
					>word</tt:span><tt:span style="BlueOnYellow"> on
					<?oxy_comment_start author="george" timestamp="20150225T112741+0200" comment="Why white????"?>white<?oxy_comment_end?>
				</tt:span></tt:p>
			<tt:p xml:id="sub13" style="textCenter" region="bottom" begin="00:00:29:09" end="00:00:31:09">
				<tt:span style="WhiteOnBlack">white on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub14" style="textCenter" region="bottom" begin="00:00:31:13" end="00:00:33:15">
				<tt:span style="WhiteOnBlack">white on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub15" style="textCenter" region="bottom" begin="00:00:33:19" end="00:00:35:20">
				<tt:span style="WhiteOnBlack">white on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub16" style="textCenter" region="bottom" begin="00:00:35:24" end="00:00:37:22">
				<tt:span style="YellowOnBlack">yellow on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub17" style="textCenter" region="bottom" begin="00:00:38:01" end="00:00:40:01">
				<tt:span style="YellowOnBlack">yellow on black</tt:span>
			</tt:p>
			<tt:p xml:id="sub18" style="textCenter" region="bottom" begin="00:00:40:05" end="00:00:42:03">
				<tt:span style="YellowOnBlack">yellow on black</tt:span>
			</tt:p>
		</tt:div>
	</tt:body>
</tt:tt>

=== oxygenxml/ebu-tt/frameworks/ebu-tt/sample/ebu-tt-sample-file-horizontal-position.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2013 by Institut fuer Rundfunktechnik GmbH. 
This work is made available under the terms of the Creative Commons Attribution-ShareAlike 3.0 license, 
http://creativecommons.org/licenses/by-sa/3.0/

This sample file should illustrate the application of EBU Tech 3360, MAPPING EBU STL (TECH 3264) TO EBU-TT SUBTITLE FILES, VER. 0.9. Please note that Version 0.9 of Tech 3360 is a draft document and may be updated, replaced or obsoleted by other documents at any time. The same applies to the sample file.
--> 
<!-- v0.1.2 -->
<?xml-stylesheet type="text/css" href="../css/ebu-tt.css"?>
<tt:tt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.w3.org/ns/ttml ../ebu-tt-xml-schema-v.1.0.1/ebutt.xsd"
 xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling"
 xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ebuttm="urn:ebu:tt:metadata" ttp:timeBase="smpte"
 xml:lang="de" ttp:cellResolution="50 30" tts:extent="704px 576px" ttp:dropMode="nonDrop"
 ttp:frameRate="25" ttp:frameRateMultiplier="1 1" ttp:markerMode="discontinuous">
	<tt:head>
		<tt:metadata>
			<ebuttm:documentMetadata>
				<ebuttm:documentEbuttVersion>v1.0</ebuttm:documentEbuttVersion>
				<ebuttm:documentTotalNumberOfSubtitles>7</ebuttm:documentTotalNumberOfSubtitles>
				<ebuttm:documentMaximumNumberOfDisplayableCharacterInAnyRow>40</ebuttm:documentMaximumNumberOfDisplayableCharacterInAnyRow>
				<ebuttm:documentStartOfProgramme>10:00:00:00</ebuttm:documentStartOfProgramme>
				<ebuttm:documentCountryOfOrigin>DE</ebuttm:documentCountryOfOrigin>
				<ebuttm:documentPublisher>Institut fuer Rundfunktechnik</ebuttm:documentPublisher>
			</ebuttm:documentMetadata>
		</tt:metadata>
		<tt:styling>
			<tt:style xml:id="defaultStyle" tts:fontFamily="monospaceSansSerif" tts:fontSize="1c 1c" tts:lineHeight="normal" tts:textAlign="center" tts:color="white" tts:backgroundColor="transparent" tts:fontStyle="normal" tts:fontWeight="normal" tts:textDecoration="none" />
			<tt:style xml:id="textWhite" tts:color="white" tts:fontSize="1c 2c"/>
			<tt:style xml:id="textCenter" tts:textAlign="center" />
			<tt:style xml:id="textLeft" tts:textAlign="start" />
			<tt:style xml:id="textRight" tts:textAlign="end" />
		</tt:styling>
		<tt:layout>
			<tt:region xml:id="bottom" tts:origin="10% 10%" tts:extent="80% 80%" tts:padding="0c" tts:displayAlign="after" tts:writingMode="lrtb"/>
		</tt:layout>
	</tt:head>
	<tt:body>
		<tt:div style="defaultStyle">
			<tt:p xml:id="sub1" style="textLeft" region="bottom" begin="00:00:00:00" end="00:00:01:08">
				<tt:span style="textWhite">left single row</tt:span>
				<tt:br/>
			</tt:p>
			<tt:p xml:id="sub2" style="textCenter" region="bottom" begin="00:00:01:12" end="00:00:02:17">
				<tt:span style="textWhite">center single row</tt:span>
				<tt:br/>
			</tt:p>
			<tt:p xml:id="sub3" style="textRight" region="bottom" begin="00:00:02:21" end="00:00:04:01"
					><tt:span style="textWhite">right single row</tt:span><tt:br/></tt:p>
			<tt:p xml:id="sub4" style="textLeft" region="bottom" begin="00:00:04:05" end="00:00:06:11">
				<tt:span style="textWhite">left</tt:span>
				<tt:br/>
				<tt:span style="textWhite">two row subtitle</tt:span>
				<tt:br/>
			</tt:p>
			<tt:p xml:id="sub5" style="textCenter" region="bottom" begin="00:00:06:15" end="00:00:08:21">
				<tt:span style="textWhite">center</tt:span>
				<tt:br/>
				<tt:span style="textWhite">two rowsubtitle</tt:span>
				<tt:br/>
			</tt:p>
			<tt:p xml:id="sub6" style="textRight" region="bottom" begin="00:00:09:00" end="00:00:11:02">
				<tt:span style="textWhite">right</tt:span>
				<tt:br/>
				<tt:span style="textWhite">two row subtitle</tt:span>
				<tt:br/>
			</tt:p>
			<tt:p xml:id="sub7" style="textCenter" region="bottom" begin="00:00:11:06" end="00:00:15:20">
				<tt:span style="textWhite">Alignment with</tt:span>
				<tt:br/>
				<tt:span style="textWhite">Spaces</tt:span>
				<tt:br/>
			</tt:p>
		</tt:div>
	</tt:body>
</tt:tt>
